modified the update forecast py and yml file

diff --git a/.github/workflows/update_forecast.yml b/.github/workflows/update_forecast.yml
--- a/.github/workflows/update_forecast.yml
+++ b/.github/workflows/update_forecast.yml
@@ -34,12 +34,18 @@ jobs:
               conda activate airquality
               pip install -r requirements.txt
         
-        - name: Run data update script
-          env:
-              GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
+        - name: Run data_capture.py
+          run: |  
+                python update_forecast.py || (echo "Error update_forecast.py" && exit 1)
+        - name: List Files
+          run: ls -R
+      
+        - name: Add and commit CSV file
           run: |
-            source $HOME/miniconda/bin/activate
-            conda activate airquality
-            python update_forecast.py
-  
+                git config user.email "${{ secrets.EMAIL }}"
+                git config user.name "foxy-dev1"
+                git add future_forecast.csv
+                git commit -m "Add generated CSV file"
+                git push origin main 
+      
        
